module.exports = {
    accesspolicy: require('./accesspolicy'),
    assetfile: require('./assetfile'),
    asset: require('./asset'),
    contentkey: require('./contentkey'),
    ingestmanifest: require('./ingestmanifest'),
    ingestmanifestasset: require('./ingestmanifestasset'),
    ingestmanifestfile: require('./ingestmanifestfile'),
    job: require('./job'),
    jobtemplate: require('./jobtemplate'),
    locator: require('./locator'),
    mediaprocessor: require('./mediaprocessor'),
    notificationendpoint: require('./notificationendpoint'),
    task: require('./task'),
    tasktemplate: require('./tasktemplate'),
};
