module.exports = {
    accesspolicy: require('./accesspolicy'),
    assetfile: require('./assetfile'),
    contentkey: require('./contentkey'),
    ingestmanifest: require('./ingestmanifest'),
    ingestmanifestfile: require('./ingestmanifestfile'),
    job: require('./job'),
    jobtemplate: require('./jobtemplate'),
    mediaprocessor: require('./mediaprocessor'),
    task: require('./task'),
    tasktemplate: require('./tasktemplate'),
    asset: require('./asset'),
    common: require('./common'),
    errordetail: require('./errordetail'),
    ingestmanifestasset: require('./ingestmanifestasset'),
    ingestmanifeststatistics: require('./ingestmanifeststatistics'),
    jobnotificationsubscription: require('./jobnotificationsubscription'),
    locator: require('./locator'),
    storageaccount: require('./storageaccount'),
    taskhistoricalevent: require('./taskhistoricalevent'),
    odata: require('./odata'),
    odata_metadata: require('./odata_metadata'),
};
